// Generated by CoffeeScript 1.3.3
(function() {
  var Boids;

  Boids = (function() {

    function Boids() {}

    Boids.prototype.initialize = function(options) {
      console.log(options);
      return alert(1);
    };

    return Boids;

  })();

}).call(this);
